### ISSUE TITLE
Morph MIDIKeys to KEYBOARD TO MIDI MAPPER, to send various MIDI commands per key

### ISSUE THREAD

**Issue by stublito** [flit/MidiKeys#13]
In the past, I made a custom wireless MIDI controller using a Mac Bluetooth Number Keypad, MIDIKeys and the MIDIPipe utility. 

I hacked the MIDIKeys XML file to accept the numkey key codes, and then sent the MIDIKeys output notes via an IAC buss to MIDIPipe, where MIDI notes can be transmuted to other MIDI commands. It worked fine, but required 2 background apps, IAC busses, a knowledge of AppleScript and MIDI bytes, and hacking the MIDIPIPE xml table.

**_So here is the request._**  An elegant, specific, compact solution that replaces hacks like mine, Bome software, MaxMSP etc. It would be the functional reverse of Charlie Robert's MIDIStroke. 

The morph is that, instead of displaying a virtual MIDI keyboard octaves of MIDI notes, there would instead be an "input = output" grid (like MIDIStroke).

A "Learn" function would capture the input key code. The output section would have 3 columns - the first column is byte 1 (type/channel) of the MIDI message,  column (byte) 2 is (usually) the MIDI note or controller number, the third byte is the value.

There would be "easy" or "Expert" modes - easy would have drop downs for Channel, Note, Controller, Program Change, Pitch Bend, and value. Expert mode would allow direct entry of hex or decimal bytes, for Machine Control etc.

Keep the Run In Background option.

I wish I could program in C, sorry I'm just a rescourceful scripter.

Stublito

**Comment by flit** [comment]
That's a pretty cool idea, thanks for taking the time to suggest it. I'd like to extend MidiKeys in that direction, for sure. Sadly, I don't get much time to work on it these days, though. But I think basically making the keymaps editable (already near the top of the list), combined with support for associating arbitrary MIDI data with keys in addition to simple notes would basically accomplish it. Learn mode would be a nice addition too.

**Comment by stublito** [comment]
Mahalo for Hawaii!

Peter

**Comment by stublito** [comment]
Mahalo form Hawaii!

Peter

**Comment by stublito** [comment]
Mahalo from Hawaii!

Peter

**Comment by flit** [comment]
Did you intend to close this issue?

**Comment by stublito** [comment]
YES

**Comment by flit** [comment]
Ok, just checking. I quite like your idea!

**Comment by stublito** [comment]
MIDIStroke is such a useful app, the reverse would be just as useful. Those
Abledon guys always need more buttons ha ha.

Sorry I'm not familiar with the way Git Hub works, should I not close the
issue?

Thanks

Peter

**Comment by flit** [comment]
Generally an issue for a new feature should be kept open until it is completed. When you close it before it's completed you are implying that you don't want or need it anymore.
