### ISSUE TITLE
MidiKeys 1.9 crashing on start

### ISSUE THREAD

**Issue by llebron** [flit/MidiKeys#21]
[MidiKeysCrash.log](https://github.com/flit/MidiKeys/files/6603132/MidiKeysCrash.log)

MidiKeys 1.9 crashing on launch in osx 11.3.

**Comment by llebron** [comment]
I tested a build from the on the same machine from the bugfix/big_sur branch and it runs well.

**Comment by flit** [comment]
Please update to [version 1.9.1](https://github.com/flit/MidiKeys/releases/tag/v1.9.1).
